#!/bin/sh

start-stop-daemon --stop --exec "/usr/sbin/hostapd" >/dev/null 2>&1
start-stop-daemon --stop --exec "/usr/sbin/dnsmasq" >/dev/null 2>&1
#systemctl stop tor.service >/dev/null 2>&1

iw wlan1mon del >/dev/null 2>&1

echo 0 > /proc/sys/net/ipv4/ip_forward
iptables -F
iptables -t nat -F

echo 'OK. FAKE AP IS STOPPED'
